apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonar-app
  template:
    metadata:
      labels:
        app: sonar-app
    spec:
      containers:
      - name: sonar-app
        image: 220309168382.dkr.ecr.eu-north-1.amazonaws.com/sonar-app:10
        ports:
        - containerPort: 8080
      # --- ADD THE SECTION BELOW ---
      imagePullSecrets:
      - name: ecr-registry-helper
